### ISSUE TITLE
Negative start and end clusters

### ISSUE THREAD

**Issue by pachadotdev** [pachadotdev/fixest2#53]
Related to https://github.com/pachadotdev/fixest2/issues/52 (and one of the causes of it)

If we print the start and end cluster values (i.e., as in https://github.com/pachadotdev/fixest2/commit/8c15559ed3cb8ede32eb8d7a3727fba8355a61cd#diff-584bf894382857a7a2c3c0ffe48c425bb04f8fffe4f911860725c9b3e9a5f7d5R624) we see

```
... etc ...

-313318728
-108417079


-108417079
-108391238


Problem getting FE, maximum iterations reached (1st order loop).>
```

Or the R session crashes immediately.

As Davis Vaughan pointed, it could be an overflow issue.

The question is why https://github.com/pachadotdev/fixest2/blob/cpp11_wip/src/05_01_misc_helpers.cpp#L590-L591 and the corresponding loop https://github.com/pachadotdev/fixest2/blob/cpp11_wip/src/05_01_misc_helpers.cpp#L593-L626 would introduce negative values :-1: 

Previously, the start and end cluster were directly created with `int start_cluster[nb_coef]` and alike, but then both GCC and LLVM complained about "ISO C++ forbids variable length array ‘start_cluster’ [-Wvla]" (i.e., here's the old code https://github.com/pachadotdev/fixest2/commit/6df7e7fc36827c157778cf7099cd92e07aaa574b#diff-584bf894382857a7a2c3c0ffe48c425bb04f8fffe4f911860725c9b3e9a5f7d5R595) .

**Comment by Antonov548** [comment]
Hi @pachadotdev 

I have investigated the problem. I would refactor some parts of function `cpp_get_fe_gnl_`, because it's not quite readable now what is happening there.

I haven't access to create pull request for this repository. But to fix the problem you can replace this lines: https://github.com/pachadotdev/fixest2/blob/6dfb429be5ea4aacf6ef3b4854acb74d567f1533/src/05_01_misc_helpers.cpp#L599-L600

with:
```C++
writable::integers tableCluster(cluster_sizes.at(q));
```

Let me know please if it make sense.
Thanks.

**Comment by pachadotdev** [comment]
> 

thanks a lot!

now I see a positive overflow, so it's moved into the right direction

If I run https://github.com/pachadotdev/fixest2/blob/cpp11_wip/dev/gdb-debug-4.R I see

```
276551082
345663211


345663211
345688975



 *** caught segfault ***
address 0x7f14d8a50fdb, cause 'memory not mapped'

Traceback:
 1: .Call(`_fixest2_cpp_get_fe_gnl_`, as.integer(Q), as.integer(N),     sumFE, dumMat, as.integer(cluster_sizes), obsCluster)
 2: cpp_get_fe_gnl(Q, N, S, dumMat, nbCluster, orderCluster)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```

**Comment by Antonov548** [comment]
For me it sometimgs works and sometimes not. Does it use some sort of generated input for the function?

I can say for now that problem is on line 778: https://github.com/pachadotdev/fixest2/blob/0c78b3f8cc2e72053f7df79aaa860884e39dcc5f/src/05_01_misc_helpers.cpp#L778

But not sure how to fix it. Needs some time to understand root cause.

**Comment by pachadotdev** [comment]
Thanks. The input for the function is described step by step in the script I mentioned, which is a script to test the code.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
